### PR TITLE
Automatically convert cassandra.yaml to a rst file

### PR DESCRIPTION
**Pull request by thobbs**

### CODE REVIEW

**Comment by pcmanus** [comment]
I like the general approach but a few remarks:
- By default, the scripts on my box gives me

```
python convert_yaml_to_rst.py ../conf/cassandra.yaml source/cassandra_yaml.rst
Traceback (most recent call last):
  File "convert_yaml_to_rst.py", line 144, in <module>
    convert(yaml_file, dest_file)
  File "convert_yaml_to_rst.py", line 70, in convert
    line = line_iter.next()
AttributeError: 'list_iterator' object has no attribute 'next'
```

because my python defaults to python 3. I can fix that by forcing python 2 but I doubt I'll be the only one running into that so if we can make it work with all version of python by default, that would be nice.
- Having all the properties like that is a good reference, but it's a bit intimidating otherwise. I think we could use some categorization of the options (at least distinguishing the option you kind of have to change, those that are often tweaked, ...). That said, that's true of the yaml file so probably the right angle is to organize the yaml and have the script recognize that. Anyway, happy to commit this has first version without that but wanted to mention it to see if we agree, in which case we can create a followup.
- Nit: I'd rename the section name "Cassandra configuration file" rather than "cassandra.yaml". The latter looks ulgy in the side TOC.

**Comment by thobbs** [comment]
> if we can make it work with all version of python by default, that would be nice

Good point.  That should be fairly easy, so I'll do that.

> Having all the properties like that is a good reference, but it's a bit intimidating otherwise. I think we could use some categorization of the options

It would be easy to add rst-style headers into the yaml file in order to organize it better.  My only concern is that reorganizing _too_ much of the yaml will make it harder for operators to diff their config with the new one.  So far my changes are limited to comments, so even though the diff will be a little messy, it should be easy to pick out the differences that matter.  It's probably still worth it to reorganize the yaml file, but if we do that, we should try to make any other changes we might want at the same time.

> I'd rename the section name "Cassandra configuration file" rather than "cassandra.yaml"

Will do.

**Comment by thobbs** [comment]
I've force-pushed to supported python3 and change the page title.

**Comment by pcmanus** [comment]
> It's probably still worth it to reorganize the yaml file, but if we do that, we should try to make any other changes we might want at the same time.

Totally. My idea here was more to create some completely orthogonal ticket about organizing the yaml file, which I submit would be useful on its own, which would be a one-off thing people would have to be aware off, and use the occasion to make it friendly that this generation. Anyway, definitively not for this ticket/branch, just wanted to have it on record.

**Comment by pcmanus** [comment]
Cherry-picked, thanks.

**Pull request closed without merging**
