### PR TITLE
8099 sstablewriters

### PR DESCRIPTION
**Pull request by tjake**
Adds SSTableWriters back and tests.  Doesn't work for counters etc.  We need to add test coverage for those.

### CODE REVIEW

**Comment by tjake** [comment]
Force pushed and removed the cell based methods so only CQL works.

**Comment by tjake** [comment]
Can you specify what kind of refactor of the existing classes you would like to see here?
Remove Simple and SimpleUnsortedSSTable writers, but keep AbstractSSTableSimpleWriter?

**Comment by pcmanus** [comment]
I would at least get rid of the name `AbstractSSTableSimpleWriter`. I don't have something very precise in mind since I haven't looked too closely. My point is that I'm pretty sure there is a number of things in the `*SimpleWriter` classes that don't make sense if we only have `CQLSSTableWriter`, so I just want to rewrite things in a way that make sense in a world where we only have `CQLSSTableWriter` (and having a class named `AbstractSSTableSimpleWriter` don't make sense, imo, though this is not saying some of the code of the class is not to be moved in `CQLSSTableWriter`).

**Comment by tjake** [comment]
Ok, re-factored and made everything but CQLSSTableWriter package local access.

**Pull request merged**
